### ISSUE TITLE
This repo is too big due to having the maven local cache files

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/devops-java-sample#76]

**Comment by JohnNiang** [comment]
I want to try to resolve this issue.

**Comment by LinuxSuRen** [comment]
Cool!

**Comment by JohnNiang** [comment]
Alright.

**Comment by JohnNiang** [comment]
I'm trying to use [this approach](https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository) to remove artifacts folder.

**Comment by JohnNiang** [comment]
#78 Resolve this issue, but may can not be merged into master branch directly.

**Comment by LinuxSuRen** [comment]
So we can reduce the size of this repo by pushing the changes directly to the master branch. Right?

But there's another thing we need to consider. What do they need to do after we removing the maven local cache files? Please consider providing a solution for people who might also want to use the cache files.

**Comment by JohnNiang** [comment]
What kind of scene needs to add offline mode in demo projects, is it reasonable in itself? This may make us more concerned.

**Comment by JohnNiang** [comment]
If offline mode is very necessary for someone, we can provide an offline packaging method for him/her.

**Comment by LinuxSuRen** [comment]
For some users, their environment has no access to the internet. It's very helpful to offer them a solution. The most important thing is that remove the maven files without a solution will be a break change for the users.

**Comment by JohnNiang** [comment]
We can guide user to execute the following command:

```bash
mvn -gs configuration/settings.xml clean verify
mvn -gs configuration/settings.xml package -DskipTests
```

The two commands above will result artifacts folder for offline mode use.

And then they can push the artifacts folder into their repo(public or private, online or offline).

**Comment by LinuxSuRen** [comment]
This is absolutely a good way to collect the cache files. How about we just do this directly? I mean we can run the command in the GitHub actions, then put those files into an image, push the image to the docker hub. So users can reuse it instead of building it every time.

**Comment by JohnNiang** [comment]
If this [merge request](https://github.com/kubesphere/devops-java-sample/pull/79) cannot merge directly, there are some steps we need to do.

1. Sync kubesphere/devops-java-sample from johnniang/devops-java-sample

   ```bash
   git clone --mirror git@github.com:JohnNiang/devops-java-sample.git
   cd devops-java-sample.git
   git remote add upstream git@github.com:kubesphere/devops-java-sample.git
   git push --mirror upstream
   ```

2. Update offline documentation

   Make sure let offline users known about how to make a maven cache in their offline environment. The following commands need to be executed by offline users.

   ```bash
   docker pull kubespheresig/devops-java-sample-cache
   docker tag kubespheresig/devops-java-sample-cache ${harbor_registry}/library/devops-java-sample-cache
   docker push ${harbor}/library/devops-java-sample-cache
   ```
